include ..\Makefile.inc

all: heat.exe


SRC = heat.cxx \
  $(SNFW_SRC)

OBJ = heat.obj \
  $(SNFW_OBJ)



heat.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:heat.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






