include ..\Makefile.inc

all: goddard.exe


SRC = goddard.cxx \
   $(SNFW_SRC)

OBJ = goddard.obj \
   $(SNFW_OBJ)






goddard.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:goddard.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






