include ..\Makefile.inc

all: missile.exe


SRC = missile.cxx \
 $(SNFW_SRC)

OBJ = missile.obj \
 $(SNFW_OBJ)



missile.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:missile.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"


