# SUITABLE COMPILERS: MICROSOFT VISUAL STUDIO 2005 and 2008
#
# SUITABLE WINDOWS VERSIONS: XP, VISTA AND 7 (32 and 64 BIT)
#
#
#
# NOTE: THE DEFAULT CONFIGURATION IS:
# MICROSOFT VISUAL STUDIO 2010 UNDER A 64 BIT VERSION OF WINDOWS
#

# DEFAULT CONFIGURATION: MS VISUAL STUDIO 2010, 64 BIT WINDOWS 

# IMPORTANT: COMMENT OUT THESE THREE LINES IF THIS VERSION IS NOT NOT USED

VCINCLUDE = "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include"

WINDOWS_H = "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include"

VCSDK  = "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include"


# UNCOMMENT THE FOLLOWING LINES TO USE MS VISUAL STUDIO 2008, 64 BIT WINDOWS 

# IMPORTANT: COMMENT OUT THESE THREE LINES IF THIS VERSION IS NOT NOT USED

# VCINCLUDE = "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include"

# WINDOWS_H = "C:\Program Files (x86)\Microsoft Visual Studio 9.0\SmartDevices\SDK\Smartphone2003\Include"

# VCSDK  = "C:\Program Files (x86)\Microsoft Visual Studio 9.0\SmartDevices\SDK\Smartphone2003\Include"



# UNCOMMENT THE THREE LINES BELOW TO USE MS VISUAL STUDIO 2008 ON A 32 BIT VERSION OF WINDOWS

# VCINCLUDE = "C:\Program Files\Microsoft Visual Studio 9.0\VC\include"

# WINDOWS_H = "C:\Program Files\Microsoft Visual Studio 9.0\SmartDevices\SDK\Smartphone2003\Include"

# VCSDK  = "C:\Program Files\Microsoft Visual Studio 9.0\SmartDevices\SDK\Smartphone2003\Include"



# UNCOMMENT THE THREE LINES BELOW TO USE MS VISUAL STUDIO 2005 UNDER A 32 BIT VERSION OF WINDOWS

# VCINCLUDE = "C:\Program Files\Microsoft Visual Studio 8\VC\include"

# VCSDK     = "C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\Include"

# WINDOWS_H = "C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\Include"



# UNCOMMENT THE THREE LINES BELOW TO USE MS VISUAL STUDIO 2005 UNDER A 64 BIT VERSION OF WINDOWS

# VCINCLUDE = "C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include"

# VCSDK     = "C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\Include"

# WINDOWS_H = "C:\Program Files (x86)\Microsoft Visual Studio 8\VC\PlatformSDK\Include"

