include ..\Makefile.inc

all: mpec.exe


SRC = mpec.cxx \
  $(SNFW_SRC)

OBJ = mpec.obj \
  $(SNFW_OBJ)



mpec.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:mpec.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






