include ..\Makefile.inc

all: crane.exe


SRC = crane.cxx \
   $(SNFW_SRC)

OBJ = crane.obj \
   $(SNFW_OBJ)




crane.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:crane.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






