include ..\Makefile.inc

all: twophro.exe


SRC = twophase_robot.cxx \
  $(SNFW_SRC)

OBJ = twophase_robot.obj \
  $(SNFW_OBJ)





twophro.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:twophro.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"




