include ..\Makefile.inc

all: brac1.exe


SRC = brac1.cxx \
  $(SNFW_SRC)

OBJ = brac1.obj \
  $(SNFW_OBJ)


brac1.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:brac1.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"







