include ..\Makefile.inc

all: lambert.exe


SRC = lambert.cxx \
  $(SNFW_SRC)

OBJ = lambert.obj \
  $(SNFW_OBJ)



lambert.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:lambert.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"





