include ..\Makefile.inc

all: sing5.exe


SRC = singular5.cxx \
  $(SNFW_SRC)

OBJ = singular5.obj \
  $(SNFW_OBJ)






sing5.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:sing5.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"





