include ..\Makefile.inc

all: twolink.exe


SRC = twolinkarm.cxx \
  $(SNFW_SRC)

OBJ = twolinkarm.obj \
  $(SNFW_OBJ)





twolink.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:twolink.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"





