include ..\Makefile.inc

all: moon.exe


SRC = moon.cxx \
   $(SNFW_SRC)

OBJ = moon.obj \
  $(SNFW_OBJ)





moon.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:moon.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






