include ..\Makefile.inc

all: twoburn.exe


SRC = twoburn.cxx \
  $(SNFW_SRC)

OBJ = twoburn.obj \
  $(SNFW_OBJ)



twoburn.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:twoburn.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"





