include ..\Makefile.inc

all: bryden.exe


SRC = bryson_denham.cxx \
  $(SNFW_SRC)

OBJ = bryson_denham.obj \
  $(SNFW_OBJ)





bryden.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:bryden.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






