include ..\Makefile.inc

all: notorious.exe


SRC = notorious.cxx \
   $(SNFW_SRC)

OBJ = notorious.obj \
   $(SNFW_OBJ)






notorious.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:notorious.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






