include ..\Makefile.inc

all: reorientation.exe


SRC = reorientation.cxx \
   $(SNFW_SRC)

OBJ = reorientation.obj \
   $(SNFW_OBJ)






reorientation.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:reorientation.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






