include ..\Makefile.inc

all: cracking.exe


SRC = cracking.cxx \
   $(SNFW_SRC)

OBJ = cracking.obj \
   $(SNFW_OBJ)






cracking.exe: $(OBJ) $(PSOPT)\lib\libpsopt.lib $(DMATRIX)\lib\libdmatrix.lib
	$(LD)  -out:cracking.exe $(OBJ) $(LIBS)  /NODEFAULTLIB:"LIBC.lib" /DEFAULTLIB:"LIBCMT.lib"






