name: Tag rolling release

on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with full history and tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Extract commit date for tag
        id: extract_tag
        run: |
          COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y-%m-%d')
          echo "TAG_NAME=$COMMIT_DATE" >> $GITHUB_ENV
          echo "tag=$COMMIT_DATE" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug check
        run: |
          echo "Tag exists: $TAG_EXISTS"
        env:
          TAG_EXISTS: ${{ steps.check_tag.outputs.exists }}

      - name: Create and push tag (if it doesn't exist)
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub Release
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          name: "Rolling Release - ${{ steps.extract_tag.outputs.tag }}"
          body: |
            This is the rolling release of PSOPT on ${{ steps.extract_tag.outputs.tag }}.
            For the latest updates, see [commit history](https://github.com/PSOPT/psopt/commits/master).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
